[theme]
primaryColor = "#F472B6"
backgroundColor = "#FCFCFC"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
